### ISSUE TITLE
Not working on ArchLinux

### ISSUE THREAD

**Issue by rilian-la-te** [glebihan/cinnamon-tracker-applet#2]
Applet shows typing menu, but does not show results, I do not know why. Package versions:

```
yaourt -Ss tracker | grep installed
extra/gnome-online-miners 3.12.0-1 [installed]
extra/libtracker-sparql 1.0.1-2 [installed]
extra/tracker 1.0.1-2 (gnome) [installed]
```

**Comment by glebihan** [comment]
Can you confirm that it's fixed with https://github.com/glebihan/cinnamon-tracker-applet/commit/709a88d95aa43c56903e07c77b5f23da6bed05ba ?

**Comment by rilian-la-te** [comment]
It`s fixed;) Now close it;)
