### ISSUE TITLE
Controlling the width, and the standardization of search results.

### ISSUE THREAD

**Issue by ghost** [glebihan/cinnamon-tracker-applet#3]
Hi, can you please add a panel, to show the url of application like a marquee tag of html, when your mouse are over some app? Do not display the url directly on main box, because can have a long size. Instead, show the archive name only. Like cinnamon menu  show only the application name, and show the description for the application in another panel. At least, do not allowed a width bigger than the corresponding monitor width for the applet's actor, right now can be bigger than the screen. You also can use two or three lines for show the description instead a marquee.

Thanks.

**Comment by ghost** [comment]
![captura de pantalla de 2014-07-09 12 50 00](https://cloud.githubusercontent.com/assets/1389572/3528650/800f1ff0-0791-11e4-954c-0557ed8f93e7.png)

**Comment by glebihan** [comment]
You're not using the latest version, where a max width is defined. 
As for the panel, I'll think about it.

**Comment by ghost** [comment]
Ok, I see... I made a pull request to fix the scroll problem... And also please, disconnect the notify::hover signal, because this cause a problem on the auto scroll feature. I not see the utility of scroll to the button on hover if you have the auto scroll enabled and like i say this cause a problem on autoscroll. Delete this line:

button.actor.connect("notify::hover", Lang.bind(this, this._scrollToButton));

And thanks.

**Comment by glebihan** [comment]
@lestcape : what autoscroll are you talking about ? that line is precisely there to implement autoscroll

**Comment by ghost** [comment]
this._scrollBox.set_auto_scrolling(true);
